version: '3'

services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - adminer-data:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  apache2:
    image: httpd:latest
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - apache2-data:/usr/local/apache2/htdocs

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    networks:
      - app-network
    volumes:
      - nginx-data:/usr/share/nginx/html

  freshrss:
    image: freshrss/freshrss:latest
    ports:
      - "8082:80"
    networks:
      - app-network
    volumes:
      - freshrss-data:/var/www/FreshRSS/data

  ubuntu:
    image: ubuntu:latest
    networks:
      - app-network
    volumes:
      - ubuntu-data:/app-data
    command: tail -f /dev/null  # Keep the container running

  kalilinux:
    image: kalilinux/kali-rolling:latest
    networks:
      - app-network
    volumes:
      - kalilinux-data:/kali-data
    command: tail -f /dev/null  # Keep the container running

networks:
  app-network:
    driver: bridge

volumes:
  adminer-data:
  mysql-data:
  apache2-data:
  nginx-data:
  freshrss-data:
  ubuntu-data:
  kalilinux-data:
